services:
  - type: web
    name: imgtools-backend
    env: node
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: "40000"
