services:
  - type: web
    name: imgtools-backend
    env: node
    region: oregon  # muda para a tua região preferida
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: "10000"  # ou outra porta, geralmente o Render passa a porta pelo env PORT
